# Default values for my-custom-chart
replicaCount: 1

image:
  repository: "docker.io/redis"  # Default image URL (can be overridden)
  tag: "latest"      # Default tag (can be overridden)
  pullPolicy: IfNotPresent
  containerPort: 6379

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

# If you want to set any environment variables, do so here.
# Otherwise, leave this commented out.
# env:          
#  - name: "GET_HOSTS_FROM"
#    value: "dns"