# Default values for my-custom-chart
replicaCount: 2

image:
  repository: "registry.k8s.io/nginx-slim"  # Default image URL (can be overridden)
  tag: "0.21"      # Default tag (can be overridden)
  pullPolicy: IfNotPresent
  containerPort: 80

persistence:
  volumeName: www
  mountPath: /usr/share/nginx/html
  size: 1Gi

service:
  enable: true  # Enable or disable the service
  # type: None
  port: 80
  clusterIP: None
  # targetPort: 80

statefulset:
  enable: false  # Enable or disable the statefulset

deployment:
  enable: true  # Enable or disable the deployment

# If you want to set any environment variables, do so here.
# Otherwise, leave this commented out.
# env:          
#  - name: "GET_HOSTS_FROM"
#    value: "dns"