apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    {{- if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    {{- end }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}