{{- if .Values.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }} # Set the service type if provided
  {{- end }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }} # Set the clusterIP if provided
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
  selector:
    app: {{ .Release.Name }}
{{- end }}