{{- if .Values.statefulset.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  labels:
    app: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-service
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: {{ .Values.persistence.volumeName | default "data" }}
              mountPath: {{ .Values.persistence.mountPath | default "/data" }}     
          env:
          {{- if .Values.env }}
            {{- range $name, $value := .Values.env }}
          - name: "{{ $name }}"
            value: "{{ $value }}"
            {{- end }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.persistence.volumeName | default "data" }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
{{- end }}
